name: Upload Website to AWS S3

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - uses: shallwefootball/s3-upload-action@master
        name: Upload to S3
        id: S3
        env:
          SOURCE_DIR: frontend/build/
          AWS_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
